name: CI - Test, Lint y Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    name: Test, Lint y Build (${{ matrix.project }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [backend, frontend]

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ${{ matrix.project }}/package-lock.json

      - name: Instalar dependencias
        working-directory: ./${{ matrix.project }}
        run: npm ci

      # --- BACKEND ---
      - name: Generar Prisma Client
        if: matrix.project == 'backend'
        working-directory: ./backend
        run: npx prisma generate

      - name: Verificar migraciones Prisma
        if: matrix.project == 'backend'
        working-directory: ./backend
        run: |
          echo "🔍 Verificando migraciones..."
          npx prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --exit-code

      # --- FRONTEND ---
      - name: Verificar TypeScript
        if: matrix.project == 'frontend'
        working-directory: ./frontend
        run: |
          echo "🔍 Verificando tipos TypeScript..."
          npx tsc --noEmit

      # --- TODOS ---
      - name: Linter
        working-directory: ./${{ matrix.project }}
        run: |
          echo "🧹 Ejecutando Linter..."
          if npm run lint --if-present; then
            echo "✅ Lint completado"
          else
            echo "❌ Linter falló"
            exit 1
          fi

      - name: Ejecutar tests
        working-directory: ./${{ matrix.project }}
        run: |
          if npm test --if-present; then
            echo "✅ Tests completados"
          else
            echo "❌ Tests fallaron"
            exit 1
          fi

      - name: Build producción
        working-directory: ./${{ matrix.project }}
        run: |
          echo "🏗️ Generando build de producción..."
          npm run build --if-present
